apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
        - name: demo-frontend
          image: vijayajala/demo-frontend:15
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: prod
spec:
  selector:
    app: demo-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vasanthavijaya/manifest-repo.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true