apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
        - name: demo-frontend
          image: vijayajala/demo-frontend:14
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: prod
spec:
  selector:
    app: demo-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP